### ISSUE TITLE
Cryptographic API Misuse Vulnerability:Do not use empty salt for KDF

### ISSUE THREAD

**Issue by gxx777** [ecies/py#324]
Hello!
First and foremost, I would like to express my sincere gratitude for your contributions to this project.

## Description:
I have identified a security vulnerability in the ecies.py v 0.4.0 project's use of null  salt for HKDF for key derivation by our cryptographic api misuse detector. The issue is that a empty salt is being used, which can lead to security vulnerabilities.

## Location
https://github.com/ecies/py/blob/master/ecies/utils/symmetric.py#L107

##  References
CWE-326: Inadequate Encryption Strength；
CWE-759: Use of a One-Way Hash without a Salt；
CWE-760: Use of a One-Way Hash with a Predictable Salt

##  Recommendations:
I recommend the following actions to mitigate the vulnerability:
use the security PRNG to generate ,for example:
```python
import os 
salt = os.urandom(16) 
```

**Comment by kigawas** [comment]
Thanks for your advice. The usage of salt for hkdf is kind of dispute. 

Basically salt is used for adding randomness if the input is not random, since our input is random (an elliptic point from a random key and user's key) and used exactly only once, salt is not needed in this case. 

You can check more details below:

https://crypto.stackexchange.com/questions/97975/applications-in-which-you-should-shouldnt-use-a-salt-with-hkdf

**Comment by gxx777** [comment]
OK,I got it.Maybe our cryptographic api misuse detector can not identify specific scene.

But I saw that the issues #82  mentioned Google’s approach（https://github.com/ecies/py/issues/82#issuecomment-520270872）
Google Tink now have added salt to KDF.
(https://github.com/google/tink/blob/master/go/subtle/hkdf.go)

**Comment by gxx777** [comment]
Thanks for your answer.It has inspired me to delve deeper into the field of cryptography.
